### PR TITLE
Schema support, multiple-fields FK, performance and more

### PR DESCRIPTION
**Pull request by teejay-87**
Hi,
following @vysl19 request, I implemented schema support and fixed other minor bugs.

List of modifications:
- schema support
- non-lowercase tables support
- multiple-fields foreign-keys support
- enabled navigation hyperlinks
- 300x performance improvement when retrieving info on FK relations from PG
- minor UI improvements in configuration window

I just need to add schema support also for functions, which will come in days.

### CODE REVIEW

**Comment by idvorkin** [comment]
_Sorry to hijack your pull request, but I want to make my own for #26.  How did you?_

1) Get the test DB running to pass unit tests
2) Get your changes to run in linqpad (did you make an LPX) 

If you reply on #26 that'd be great.

**Comment by fknx** [comment]
Thanks a lot for your work, I've merged your pull request. Has there been a technical reason for you to add the constraint name to the associations or out of personal preference?

**Comment by teejay-87** [comment]
If I remember well, I added it to distinguish them in the case you have more than one relation between the same two tables. We have some example in our suite's DB.

**Comment by fknx** [comment]
Okay good to know. I've reverted this change since it wasn't possible any more to access the association property from the code (since it contained illegal characters), but I've implemented a collision detection to avoid adding two properties with the same name (a number will be added to the property's name if a property with the same name already exists) and I've added a tooltip to the association's explorer item which contains the constraint name.

**Comment by teejay-87** [comment]
Ok, @fknx.
That seems to be a good compromise!
Thanks for quoting me in the release info of versione 0.30.

I'll try to implement schema support even for functions, but in this period I only have a little time to code.

**Pull request merged**
