### PR TITLE
Schema support for Postgresql

### PR DESCRIPTION
**Pull request by vysl19**
Hi, I developed the schema support for linqpad. I would be appriciated if you can check my commits. My team lead is always using linqpad and he is using my new lpx file without any errors. I hope it would be useful for other people too. Thanks

### CODE REVIEW

**Comment by fknx** [comment]
Sorry for the late response and thanks for the pull request. I'll try to look into it asap (hopefully this weekend).

**Comment by zatuliveter** [comment]
Hello, any news on schema support?

**Comment by fknx** [comment]
I'm closing this since schema support has been implemented. I've merged a different pull request because it contained several additional changes. Thanks a lot for your work and sorry for the delayed response.

**Comment by zatuliveter** [comment]
Thanks!

**Pull request closed without merging**
